export const sampleTexts = [
  'The quick brown fox jumps over the lazy dog. This classic pangram contains all twenty-six letters of the English alphabet and has been used for typing practice for decades',
  'In the digital age, typing skills have become essential for communication, work, and creativity. Fast and accurate typing can significantly improve productivity and efficiency.',
  'Practice makes perfect when it comes to developing muscle memory for keyboard layouts. Regular typing exercises help build speed while maintaining accuracy over time.',
  'Modern keyboards come in various forms, from mechanical switches to membrane designs. Each type offers different tactile feedback and response characteristics for typists.',
  'Touch typing involves using all ten fingers without looking at the keyboard. This technique allows for faster input speeds and reduced strain during extended typing sessions.',
  'Typing speed and accuracy are essential for productivity and efficiency. Regular typing exercises help build speed while maintaining accuracy over time. By regularly practicing, you can improve your typing skills and become more efficient. The key to success is consistency and practice.',
  'The evolution of computer technology has revolutionized the way we work, communicate, and access information. From the early days of punch cards to modern touch screens, the interface between humans and machines has continuously evolved. Today, we rely on various input methods including keyboards, mice, voice recognition, and gesture controls to interact with our digital devices.',
  'Programming languages serve as the foundation for building software applications that power our modern world. Each language has its own syntax, rules, and best practices that developers must master. Popular languages like JavaScript, Python, Java, and C++ each offer unique advantages for different types of projects, from web development to artificial intelligence and system programming.',
  'The internet has transformed global communication, making it possible to connect with people across continents in real-time. Social media platforms, video conferencing tools, and instant messaging services have created new ways for individuals and businesses to share information, collaborate on projects, and build communities. This digital connectivity has also raised important questions about privacy, security, and the responsible use of technology.',
  'Artificial intelligence and machine learning are reshaping industries and creating new possibilities for automation and decision-making. These technologies can analyze vast amounts of data, recognize patterns, and make predictions that would be impossible for humans to process manually. As AI continues to advance, it presents both opportunities for innovation and challenges regarding ethics, job displacement, and the need for new skills and education.',
  'Climate change represents one of the most pressing challenges of our time, requiring immediate action from governments, businesses, and individuals worldwide. Rising global temperatures, melting ice caps, and extreme weather events are already affecting ecosystems and human communities. Addressing this crisis demands a comprehensive approach including renewable energy adoption, sustainable agriculture practices, and international cooperation on environmental policies.',
  'The human brain is an incredibly complex organ that processes information, controls bodily functions, and enables consciousness. Neuroscientists continue to discover new insights about how neurons communicate, how memories are formed and stored, and how different regions of the brain work together to create our thoughts, emotions, and behaviors. Understanding the brain\'s mechanisms could lead to breakthroughs in treating neurological disorders and enhancing cognitive abilities.',
  'Space exploration has captured humanity\'s imagination for generations, driving technological innovation and expanding our understanding of the universe. Recent missions to Mars, the discovery of exoplanets, and advances in rocket technology have renewed interest in space travel and colonization. These endeavors require international collaboration, massive resources, and cutting-edge engineering to overcome the challenges of surviving in the harsh environment of space.',
  'The history of literature spans thousands of years and encompasses countless cultures, languages, and storytelling traditions. From ancient epics like the Iliad and Odyssey to modern novels and poetry, literature reflects the human experience and provides insights into different societies and time periods. Great works of literature continue to influence contemporary culture and inspire new generations of writers and readers around the world.',
  'Music is a universal language that transcends cultural boundaries and connects people across different backgrounds and experiences. From classical symphonies to contemporary pop songs, music has the power to evoke emotions, tell stories, and bring communities together. The evolution of music technology, from acoustic instruments to digital production tools, has expanded the possibilities for creative expression and made music more accessible to people worldwide.',
];

export function getRandomText(): string {
  return sampleTexts[Math.floor(Math.random() * sampleTexts.length)];
}

export function capitalizeFirst(text: string): string {
    return text.charAt(0).toUpperCase() + text.slice(1)
}
