/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpectatorRouteImport } from './routes/spectator'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as IndexRouteImport } from './routes/index'

const SpectatorRoute = SpectatorRouteImport.update({
  id: '/spectator',
  path: '/spectator',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competition'
    | '/session'
    | '/settings'
    | '/solo'
    | '/spectator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/competition' | '/session' | '/settings' | '/solo' | '/spectator'
  id:
    | '__root__'
    | '/'
    | '/competition'
    | '/session'
    | '/settings'
    | '/solo'
    | '/spectator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionRoute: typeof CompetitionRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SoloRoute: typeof SoloRoute
  SpectatorRoute: typeof SpectatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spectator': {
      id: '/spectator'
      path: '/spectator'
      fullPath: '/spectator'
      preLoaderRoute: typeof SpectatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionRoute: CompetitionRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SoloRoute: SoloRoute,
  SpectatorRoute: SpectatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
