/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpectatorRouteImport } from './routes/spectator'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentIndexRouteImport } from './routes/tournament/index'
import { Route as TournamentTournamentIdRouteImport } from './routes/tournament/$tournamentId'
import { Route as TournamentTournamentIdLobbyRouteImport } from './routes/tournament/$tournamentId/lobby'
import { Route as TournamentTournamentIdCreateRouteImport } from './routes/tournament/$tournamentId/create'
import { Route as TournamentTournamentIdBracketRouteImport } from './routes/tournament/$tournamentId/bracket'

const SpectatorRoute = SpectatorRouteImport.update({
  id: '/spectator',
  path: '/spectator',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIndexRoute = TournamentIndexRouteImport.update({
  id: '/tournament/',
  path: '/tournament/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentTournamentIdRoute = TournamentTournamentIdRouteImport.update({
  id: '/tournament/$tournamentId',
  path: '/tournament/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentTournamentIdLobbyRoute =
  TournamentTournamentIdLobbyRouteImport.update({
    id: '/lobby',
    path: '/lobby',
    getParentRoute: () => TournamentTournamentIdRoute,
  } as any)
const TournamentTournamentIdCreateRoute =
  TournamentTournamentIdCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => TournamentTournamentIdRoute,
  } as any)
const TournamentTournamentIdBracketRoute =
  TournamentTournamentIdBracketRouteImport.update({
    id: '/bracket',
    path: '/bracket',
    getParentRoute: () => TournamentTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRouteWithChildren
  '/tournament': typeof TournamentIndexRoute
  '/tournament/$tournamentId/bracket': typeof TournamentTournamentIdBracketRoute
  '/tournament/$tournamentId/create': typeof TournamentTournamentIdCreateRoute
  '/tournament/$tournamentId/lobby': typeof TournamentTournamentIdLobbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRouteWithChildren
  '/tournament': typeof TournamentIndexRoute
  '/tournament/$tournamentId/bracket': typeof TournamentTournamentIdBracketRoute
  '/tournament/$tournamentId/create': typeof TournamentTournamentIdCreateRoute
  '/tournament/$tournamentId/lobby': typeof TournamentTournamentIdLobbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competition': typeof CompetitionRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/solo': typeof SoloRoute
  '/spectator': typeof SpectatorRoute
  '/tournament/$tournamentId': typeof TournamentTournamentIdRouteWithChildren
  '/tournament/': typeof TournamentIndexRoute
  '/tournament/$tournamentId/bracket': typeof TournamentTournamentIdBracketRoute
  '/tournament/$tournamentId/create': typeof TournamentTournamentIdCreateRoute
  '/tournament/$tournamentId/lobby': typeof TournamentTournamentIdLobbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competition'
    | '/session'
    | '/settings'
    | '/solo'
    | '/spectator'
    | '/tournament/$tournamentId'
    | '/tournament'
    | '/tournament/$tournamentId/bracket'
    | '/tournament/$tournamentId/create'
    | '/tournament/$tournamentId/lobby'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competition'
    | '/session'
    | '/settings'
    | '/solo'
    | '/spectator'
    | '/tournament/$tournamentId'
    | '/tournament'
    | '/tournament/$tournamentId/bracket'
    | '/tournament/$tournamentId/create'
    | '/tournament/$tournamentId/lobby'
  id:
    | '__root__'
    | '/'
    | '/competition'
    | '/session'
    | '/settings'
    | '/solo'
    | '/spectator'
    | '/tournament/$tournamentId'
    | '/tournament/'
    | '/tournament/$tournamentId/bracket'
    | '/tournament/$tournamentId/create'
    | '/tournament/$tournamentId/lobby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionRoute: typeof CompetitionRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SoloRoute: typeof SoloRoute
  SpectatorRoute: typeof SpectatorRoute
  TournamentTournamentIdRoute: typeof TournamentTournamentIdRouteWithChildren
  TournamentIndexRoute: typeof TournamentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spectator': {
      id: '/spectator'
      path: '/spectator'
      fullPath: '/spectator'
      preLoaderRoute: typeof SpectatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/': {
      id: '/tournament/'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$tournamentId': {
      id: '/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/tournament/$tournamentId'
      preLoaderRoute: typeof TournamentTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$tournamentId/lobby': {
      id: '/tournament/$tournamentId/lobby'
      path: '/lobby'
      fullPath: '/tournament/$tournamentId/lobby'
      preLoaderRoute: typeof TournamentTournamentIdLobbyRouteImport
      parentRoute: typeof TournamentTournamentIdRoute
    }
    '/tournament/$tournamentId/create': {
      id: '/tournament/$tournamentId/create'
      path: '/create'
      fullPath: '/tournament/$tournamentId/create'
      preLoaderRoute: typeof TournamentTournamentIdCreateRouteImport
      parentRoute: typeof TournamentTournamentIdRoute
    }
    '/tournament/$tournamentId/bracket': {
      id: '/tournament/$tournamentId/bracket'
      path: '/bracket'
      fullPath: '/tournament/$tournamentId/bracket'
      preLoaderRoute: typeof TournamentTournamentIdBracketRouteImport
      parentRoute: typeof TournamentTournamentIdRoute
    }
  }
}

interface TournamentTournamentIdRouteChildren {
  TournamentTournamentIdBracketRoute: typeof TournamentTournamentIdBracketRoute
  TournamentTournamentIdCreateRoute: typeof TournamentTournamentIdCreateRoute
  TournamentTournamentIdLobbyRoute: typeof TournamentTournamentIdLobbyRoute
}

const TournamentTournamentIdRouteChildren: TournamentTournamentIdRouteChildren =
  {
    TournamentTournamentIdBracketRoute: TournamentTournamentIdBracketRoute,
    TournamentTournamentIdCreateRoute: TournamentTournamentIdCreateRoute,
    TournamentTournamentIdLobbyRoute: TournamentTournamentIdLobbyRoute,
  }

const TournamentTournamentIdRouteWithChildren =
  TournamentTournamentIdRoute._addFileChildren(
    TournamentTournamentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionRoute: CompetitionRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SoloRoute: SoloRoute,
  SpectatorRoute: SpectatorRoute,
  TournamentTournamentIdRoute: TournamentTournamentIdRouteWithChildren,
  TournamentIndexRoute: TournamentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
